#!/bin/bash

#Този пример показва как може да се подават променливи редм с извикването на скрипта
#
# Чрез следната команда се записват в променливите стоиностите Stoian  и Banchev
# ./les0-1 Stoian banchev

first=$1 # чрез $1 се приема първата променлива
second=$2

echo "Your name is $first $second"
shift
echo "Your name is $1 $2"
shift
echo "Your name is $1 $2"

