#!/bin/bash
# posit-param: script to view command line parameters


# Демонстрира работата на параметри въведеби в един ред с извикеането на скрипта
# ==============================================================================
# За да тествате резултата опитайте следните извикеания на скрипта
# ./les16 a b c d e f
# ./les16 *
#

echo "
Here start the script for comand line parameter
------------------------------------------------
You enter $# comand line parameter 
"
echo "
\$0 = $0
\$1 = $1
\$2 = $2
\$3 = $3
\$4 = $4
\$5 = $5
\$6 = $6
\$7 = $7
\$8 = $8
\$9 = $9
"


echo "
Start second part of script
================================
"

count=1

while [[ $# -gt 0 ]]; do
    echo "Argument $count = $1"
    count=$((count + 1))
    shift # специална команда която измества $2 в $1 и т.н.
done