#!/bin/bash
# case-menu: a menu driven system information program


#
#Пример 1 -Демонстрира менюто от les11 изппълнено с case
#================================================

clear
echo "
Please Select:
1. Display System Information
2. Display Disk Space
3. Display Home Space Utilization
0. Quit
"
read -p "Enter selection [0-3] > "

case $REPLY in

0)  echo "Program terminated."
    #exit
    ;;

1)  echo "Hostname: $HOSTNAME"
    uptime
    ;;

2)  df -h
    ;;

3)  if [[ $(id -u) -eq 0 ]]; then

        echo "Home Space Utilization (All Users)"
        du -sh /home/*
    else

        echo "Home Space Utilization ($USER)"
        du -sh $HOME
    fi
    ;;

*)  echo "Invalid entry" >&2
    #exit 1
    ;;
esac

# Задържане на резултата от първия пример
sleep 3 
clear

#Пример 2 -Демонстрира пример за възможни условия със case и regexp
#================================================

read -p "enter word > "
case $REPLY in

[:alpha:])      echo "is a single alphabetic character." ;;
[ABC][0-9])     echo "is a A,B or C fowolled by digit." ;;
???)             echo "is a three charter long." ;;
*.txt)          echo "is a txt file." ;;
*)              echo "is somthing else." ;;

esac

# Задържане на резултата от втория пример
sleep 3
clear


#Пример 3 Демонстрира как case изпълнява само едно условие, на което отговаря входа 
# ако няма символ & в края на 
#================================================

echo "
Start of 3rd example of this script
Type a charter to see difrent output
==============================================
"
read -n 1 -p "Type a character > "
echo "

Outputh with case without & 
=======================================
"
case $REPLY in

[[:upper:]])    echo "'$REPLY' is upper case." ;;
[[:lower:]])    echo "'$REPLY' is lower case." ;;
[[:alpha:]])    echo "'$REPLY' is alphabetic." ;;
[[:digit:]])    echo "'$REPLY' is a digit." ;;
[[:graph:]])    echo "'$REPLY' is a visible character." ;;
[[:punct:]])    echo "'$REPLY' is a punctuation symbol." ;;
[[:space:]])    echo "'$REPLY' is a whitespace character." ;;
[[:xdigit:]])   echo "'$REPLY' is a hexadecimal digit." ;;

esac

echo "
Outputh with case without & 
=======================================
"

case $REPLY in

[[:upper:]])    echo "'$REPLY' is upper case." ;;&
[[:lower:]])    echo "'$REPLY' is lower case." ;;&
[[:alpha:]])    echo "'$REPLY' is alphabetic." ;;&
[[:digit:]])    echo "'$REPLY' is a digit." ;;&
[[:graph:]])    echo "'$REPLY' is a visible character." ;;&
[[:punct:]])    echo "'$REPLY' is a punctuation symbol." ;;&
[[:space:]])    echo "'$REPLY' is a whitespace character." ;;&
[[:xdigit:]])   echo "'$REPLY' is a hexadecimal digit." ;;&

esac



