#!/bin/bash

# Отпечатва числата от едно до десет
for i in {1..10}; do

    printf "$i "

done

echo "" # Зарежда нов ред

# Отпечатва малките букви от а до z
for i in {a..z}; do

    printf "$i " 

done

echo ""

# Отпечатва всички файлове в текущата папка, чиито имена започват с les
for i in les*; do

    printf "$i "

done

echo ""
