#!/bin/bash
# read-ifs: read fields from a file

FILE=/etc/passwd #файл и неговото разположение в дисковото пространство

read -p "Enter a username > " user_name #въвеждане на потребителското име което е регистрирано моето е sb
file_info=$(grep "^$user_name:" $FILE) #отсяване на реда чрез regex, в който се намира потребителското име

if [ -n "$file_info" ]; then
    IFS=":" read user pw uid gid name home shell <<< "$file_info" #този рез доста особен на стр.428 е описано защо се прави така
    echo "User =      '$user'"                                      #и защо не може да се използва пайпинг
    echo "UID =       '$uid'"
    echo "GID =       '$gid'"
    echo "Full Name = '$name'"
    echo "Home Dir. = '$home'"
    echo "Shell =     '$shell'"
else
    echo "No such user '$user_name'" >&2
    exit 1
fi